import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Al's Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col relative`}
      >
        <Navbar />
        {/* <nav className="p-5 flex items-center justify-end">
          <button className="w-10 h-10 rounded bg-white/20 relative">
            <GripIcon className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
          </button>
        </nav> */}
        <main className="max-w-xl p-5 w-full mx-auto h-full flex-2/4">
          {children}
        </main>
        <footer className="h-40 p-5">
          <h2>Also me</h2>
          <ul className="mt-1 text-sm">
            <li>
              <p>
                <span className="w-20 inline-block">Mail</span>
                <a className="ml-16">syahrastanialtaf@gmail.com</a>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Twitter</span>
                <a className="ml-16">@altafsyh_</a>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Dribble</span>
                <a className="ml-16">@altafsyh_</a>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Medium</span>
                <a className="ml-16">@altafsyh_</a>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Fenulis</span>
                <a className="ml-16">@tanee</a>
              </p>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
