import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Link from "next/link";

const geistSans = Geist({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Al's Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased min-h-screen flex flex-col relative`}
      >
        <Navbar />
        <main className="max-w-xl p-5 w-full mx-auto h-full flex-2/4">
          {children}
        </main>
        <footer className="max-w-xl xl:max-w-none h-40 p-5 xl:fixed bottom-0 left-0 mx-auto xl:mx-0 w-full">
          <h2 className="font-medium text-lg">Also me</h2>
          <ul className="mt-1 text-sm">
            <li>
              <p>
                <span className="w-20 inline-block">Mail</span>
                <Link
                  href="mailto:syahrastanialtaf@gmail.com"
                  className="ml-10 cursor-pointer hover:underline underline-offset-2"
                >
                  syahrastanialtaf@gmail.com
                </Link>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Twitter</span>
                <Link
                  href="https://x.com/altafsyh_"
                  target="_blank"
                  className="ml-10 cursor-pointer hover:underline underline-offset-2"
                >
                  @altafsyh_
                </Link>
              </p>
            </li>
            <li>
              <p>
                <span className="w-20 inline-block">Fenulis</span>
                <Link
                  href="https://www.fenulis.com/tanee"
                  target="_blank"
                  className="ml-10 cursor-pointer hover:underline underline-offset-2"
                >
                  @tanee
                </Link>
              </p>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
