import IdCardIcon from "@/components/id-card-icon";
import { cn } from "@/lib/utils";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Al's Space",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section id="hero__section" className="flex gap-3 items-center">
        <div className="w-14 aspect-square rounded-lg shrink-0 bg-red-300"></div>
        <div>
          <h1>Altaf Syahrastani</h1>
          <p className="text-sm">
            Frontend Developer @{" "}
            <Link
              href="https://technopartner.id/"
              target="_blank"
              className="underline underline-offset-2"
            >
              Technopartner
            </Link>
          </p>
        </div>
      </section>
      <section className="mt-10">
        <h2>Profile</h2>
        <p className="mt-1 text-sm">
          Call me Al, a frontend developer based on Yogyakarta. Currently
          I&apos;m working as Frontend Developer for{" "}
          <Link
            href="https://technopartner.id/"
            target="_blank"
            className="underline underline-offset-2"
          >
            Technopartner Indonesia
          </Link>
          . Responsible for turning design and make things works.
        </p>
      </section>
      <section className="mt-10">
        <h2>Projects</h2>
        <p className="mt-1 text-sm">
          I love build and want to explore into product things.
        </p>
        <div className="mt-3 flex gap-2">
          <div
            className={cn(
              "w-3/4 h-40 rounded-xl p-3 bg-gray-800/70 border border-white/20",
              "flex flex-col justify-between gap-5",
              "hover:scale-[1.015] transition-transform"
            )}
          >
            <div>
              <h3 className="font-bold">Nawasena</h3>
              <p className="text-sm">Personal AI-Assisted Expense Tracker.</p>
            </div>
            <div className="flex justify-between text-sm items-center">
              <Link
                href="/"
                className="bg-white/10 border border-white/10 rounded-sm px-2 py-1"
              >
                View Project
              </Link>
              <div className="flex">
                <Link href="/">Coming Soon</Link>
              </div>
            </div>
          </div>
          <div className="w-1/4 h-40 rounded-xl border border-white/20 bg-gray-800/70"></div>
        </div>
      </section>
      <section className="mt-10">
        <h2>Works</h2>
        <ul className="mt-3 flex flex-col gap-2">
          <li
            className={cn(
              "w-full flex gap-3 items-center border border-transparent p-2 cursor-default",
              "hover:bg-gray-800/80 hover:border-white/20 transition-all hover:rounded group"
            )}
          >
            <div
              className={cn(
                "relative shrink-0 w-10 h-10 rounded bg-gray-800/80 border border-white/20",
                "group-hover:scale-95 transition-transform duration-200"
              )}
            >
              <IdCardIcon
                className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
                size={25}
              />
            </div>
            <div className="text-sm">
              <h3>Frontend Developer @ Technopartner</h3>
              <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
            </div>
          </li>
          <li
            className={cn(
              "w-full flex gap-3 items-center border border-transparent p-2 cursor-default",
              "hover:bg-gray-800/80 hover:border-white/20 transition-all hover:rounded group"
            )}
          >
            <div
              className={cn(
                "relative shrink-0 w-10 h-10 rounded bg-gray-800/80 border border-white/20",
                "group-hover:scale-95 transition-transform duration-200"
              )}
            >
              <IdCardIcon
                className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
                size={25}
              />
            </div>
            <div className="text-sm">
              <h3>Freelance Software Developer</h3>
              <p>I&apos;m open to collaborate</p>
            </div>
          </li>
        </ul>
      </section>
      <section className="mt-10">
        <h2>Writings</h2>
        <p className="text-sm mt-1">
          I spent my idle hours on my hobbies, and writings is one of them. I do
          write some blog that some of them published on{" "}
          <Link
            href="https://www.fenulis.com/tanee"
            target="_blank"
            className="underline underline-offset-2 cursor-alias"
          >
            Fenulis
          </Link>{" "}
          and this website as well.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-5">
          <Link
            href="/"
            className={cn(
              "border border-white/20 p-3 rounded-lg",
              "hover:scale-[1.015] hover:bg-gray-800/80 transition-all group"
            )}
          >
            <h3>The Emotion That Feels Like Static</h3>
            <p className="text-sm line-clamp-2 text-gray-400 group-hover:text-white transition-colors">
              I told my therapist I&apos;ve been fine with feeling nothing. She
              didn&apos;t look convinced. To be honest, neither was I.
            </p>
          </Link>
          <Link
            href="/"
            className={cn(
              "border border-white/20 p-3 rounded-lg",
              "hover:scale-[1.015] hover:bg-gray-800/80 transition-all group"
            )}
          >
            <h3>The City Taught Me How Much I Loved the Quiet Moments</h3>
            <p className="text-sm line-clamp-2 text-gray-400 group-hover:text-white transition-colors">
              I remember coming home from work, tired but content, and sitting
              down for dinner with my parents in our small living room. We
              didn’t talk much—just casual small talk over the background noise
              of a TV show none of us was watching. It wasn’t anything special,
              but it was warm.
            </p>
          </Link>
        </div>
      </section>
    </>
  );
}
